### PR TITLE
Add PHP 8.2 support

### PR DESCRIPTION
**Pull request by fezfez**

### CODE REVIEW

**Comment by fezfez** [comment]
need https://github.com/phpspec/prophecy/pull/571

**Comment by Ocramius** [comment]
@fezfez can we drop the dependency instead, and rewrite some of the tests? 🤔

**Comment by fezfez** [comment]
> @fezfez can we drop the dependency instead, and rewrite some of the tests? thinking

i try :)

**Comment by fezfez** [comment]
@Ocramius done

**Review by Ocramius — APPROVED** [review]
Most excellent, thanks!

**Pull request merged**
