### PR TITLE
Remove support for PHP 8.0, Add support for PHP 8.3

### PR DESCRIPTION
**Pull request by glo71317**
|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### CODE REVIEW

**Comment by glo71317** [comment]
@Ocramius along with this PR, Following PRs are ready for merge.

```
https://github.com/laminas/laminas-file/pull/15
https://github.com/laminas/laminas-mvc/pull/159
https://github.com/laminas/laminas-oauth/pull/21
https://github.com/laminas/laminas-server/pull/72
https://github.com/laminas/laminas-mvc-plugin-flashmessenger/pull/36
```

Few below prs having some dependencies issue
```
https://github.com/laminas/laminas-db/pull/293
https://github.com/laminas/laminas-cache-storage-deprecated-factory/pull/5
```
If you don't mind can you please take a look above PRs on priorities so that we can unblock to update dependencies in Magento side.

**Comment by Ocramius** [comment]
These two need a check by @laminas/technical-steering-committee, since the entire PHPCS changeset got suppressed:

 * https://github.com/laminas/laminas-file/pull/15
 * https://github.com/laminas/laminas-oauth/pull/21

`laminas/laminas-db` will probably happen sometime in 2024 due to MS SQL Server support simply not being there: https://github.com/laminas/laminas-db/pull/293#issuecomment-1781196353 If we don't test it, we don't support it, and dropping support is a major BC break.

**Comment by glo71317** [comment]
@Ocramius Thank you so much for quick response!
https://github.com/laminas/laminas-file/pull/15
https://github.com/laminas/laminas-oauth/pull/21
for above both the pr changes, we have entire PHPCS changeset got suppressed as of now because if we go for fixes then lot of file changes will be there if you are agree then we can contribute for the same.

laminas/laminas-db will probably happen sometime in 2024 - It will too late for us, Please discuss internally and let us know about all above three pr changes. there is any way to get it done as soon as possible.

We are ready to instant help regarding the same. Thanks

**Comment by Ocramius** [comment]
> laminas/laminas-db will probably happen sometime in 2024 - It will too late for us, Please discuss internally and let us know about all above three pr changes. there is any way to get it done as soon as possible.

You can certainly get in contact with Microsoft about their SQL Server support: that would help speed things up.

We depend on it, and won't release without testing that first: I can imagine they'd need time to do a release themselves too.

I would also take a moment to remind that you (personally and Adobe Commerce) are a user of a freely provided "as is" library: we do what we can, when we can, and also when we feel like it.
If Adobe wants to get guaranteed release schedules on their own terms, I'd expect them to get in direct contact with [the TSC and Linux foundation](https://getlaminas.org/about/foundation) to have some of our work sponsored properly.

**Review by gsteel — APPROVED** [review]
Thanks @glo71317 - This patch LGTM 👍

**Comment by gsteel** [comment]
@Ocramius - merging this patch because it looks like discussion relates to other libs

**Pull request merged**
